import type { Metadata } from 'next'


// import css
import '@/styles/globals.css'


// import components
import { Toaster } from 'react-hot-toast'
import AuthContext from '@/context/authContext'


export const metadata: Metadata = {
    title: 'Swift Chat',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
            </head>
            <body>
                <AuthContext>
                    <Toaster />
                    <main>{children}</main>
                </AuthContext>
            </body>
        </html>
    )
}
