import type { Metadata } from 'next'

// import css
import '@/styles/globals.css'

export const metadata: Metadata = {
    title: 'Swift Chat',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    )
}
